### ISSUE TITLE
Initial translate position

### ISSUE THREAD

**Issue by gnuletik** [SharifClick/svelte-swipe#55]
Hi,

In order to reduce layout shift on page load, would it be possible to set an initial transform value ?

I set this value in my component for now.
```css
:global(.swipeable-item:not(.is-active)) {
  transform: translate3d(100vw, 0, 0);
}
```

Thanks!
